version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    networks:
      - my_network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A proxy_list worker -l DEBUG
    volumes:
      - .:/django
    depends_on:
      - redis
      - db
    networks:
      - my_network
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A proxy_list beat -l info
    volumes:
      - .:/django
    depends_on:
      - redis
      - db
    networks:
      - my_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data:
